### ISSUE TITLE
TypeError: an integer is required (got type str) ini Pyarrow

### ISSUE THREAD

**Issue by kychanbp** [awslabs/aws-data-wrangler#441]
*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

I received the following error:
```
  File "etl_fp_ledger_landing_tables.py", line 165, in extract_data
    df = wr.db.read_sql_query(query, con=sql_engine)
  File "/Users/johnchan/.local/share/virtualenvs/fp_ledger-kbdDDZPp/lib/python3.8/site-packages/awswrangler/db.py", line 438, in read_sql_query
    return _records2df(
  File "/Users/johnchan/.local/share/virtualenvs/fp_ledger-kbdDDZPp/lib/python3.8/site-packages/awswrangler/db.py", line 197, in _records2df
    array: pa.Array = pa.array(obj=col_values, safe=safe)  # Creating Arrow array
  File "pyarrow/array.pxi", line 296, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
TypeError: an integer is required (got type str)
```
The error said an integer is required. I have tried to be more specific on the query to identify which columns causing the problem. It turns out to be the datetime column. In MySQL, the data type is `datetime` and in glue the data type is `timestamp`.

There is no problem for other tables. Not sure why this happen.

**Comment by igorborgest** [comment]
Hi @kychanbp,

I've tried to replicate your issue, but I couldn't by now. Can you help me to do it?

I'm trying something like:

```py3
import awswrangler as wr
import pandas as pd
from datetime import datetime

ts = lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S.%f")
dt = lambda x: datetime.strptime(x, "%Y-%m-%d").date()

df = pd.DataFrame(
    {
        "c0": [ts("2020-01-01 00:00:00.0"), None, ts("2020-01-02 00:00:01.0")],
        "c1": [dt("2020-01-01"), None, dt("2020-01-02")],
    }
)

engine = wr.catalog.get_engine("aws-data-wrangler-mysql")
wr.db.to_sql(df, engine, name="test", index=False, if_exists="replace")
df2 = wr.db.read_sql_query("SELECT * FROM test", engine)
assert df.equals(df2)
```

**Comment by kychanbp** [comment]
No assertion error. But maybe I need to run a crawler on the database to try again.

**Comment by igorborgest** [comment]
@kychanbp I think the crawler (and the Glue Catalog) doesn't have relation with your error.
Seems to be specific to the direct extraction from MySQL to Pandas DataFrame.
That's why trying to replicate it in a isolated code snippet would be the best strategy to understand it.

**Comment by kychanbp** [comment]
@igorborgest 

I have tried the following:
```
import awswrangler as wr
import pandas as pd
from datetime import datetime

engine = wr.catalog.get_engine("fp_prod_db")
df2 = wr.db.read_sql_query("SELECT * FROM banks", engine)
```

I got the error 
```
Traceback (most recent call last):
  File "replicate.py", line 6, in <module>
    df2 = wr.db.read_sql_query("SELECT * FROM banks", engine)
  File "/Users/johnchan/.local/share/virtualenvs/aws_data_wrangler_issue441-f6GMmtUF/lib/python3.8/site-packages/awswrangler/db.py", line 438, in read_sql_query
    return _records2df(
  File "/Users/johnchan/.local/share/virtualenvs/aws_data_wrangler_issue441-f6GMmtUF/lib/python3.8/site-packages/awswrangler/db.py", line 197, in _records2df
    array: pa.Array = pa.array(obj=col_values, safe=safe)  # Creating Arrow array
  File "pyarrow/array.pxi", line 296, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
TypeError: an integer is required (got type str)
```

The following is the columns in the table `banks`
```
CREATE TABLE `banks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bank_name` varchar(255) DEFAULT NULL,
  `account_name` varchar(255) DEFAULT NULL,
  `account_no` varchar(255) DEFAULT NULL,
  `bank_address` varchar(255) DEFAULT NULL,
  `bank_address_2` varchar(255) DEFAULT NULL,
  `contact_person` varchar(255) DEFAULT NULL,
  `contact_tel` varchar(255) DEFAULT NULL,
  `contact_tel_area_code` varchar(255) DEFAULT NULL,
  `created_on` datetime(6) NOT NULL,
  `modified_on` datetime(6) NOT NULL,
  `status` varchar(3) NOT NULL,
  `company_id` int(11) DEFAULT NULL,
  `swift_code` varchar(255) DEFAULT NULL,
  `external_bank_id` varchar(255) DEFAULT NULL,
  `external_name` varchar(255) DEFAULT NULL,
  `currency` varchar(3) DEFAULT NULL,
  `is_default` tinyint(1) NOT NULL,
  `bank_type` varchar(255) DEFAULT NULL,
  `funder_id` int(11) DEFAULT NULL,
  `buyer_id` int(11) DEFAULT NULL,
  `country_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
hided some foreign keys
) ENGINE=InnoDB AUTO_INCREMENT=451 DEFAULT CHARSET=utf8;
```

**Comment by igorborgest** [comment]
Could you test with our new function, please?

[wr.mysql.read_sql_query()](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.mysql.read_sql_query.html)

**Comment by igorborgest** [comment]
Closing by inactivity.

**Comment by maiconrocha** [comment]
@igorborgest I got the error `TypeError: an integer is required (got type str) ` when using either `wr.mysql.read_sql_query()` or `wr.mysql.read_sql_table()` and specifying explicitly the pyarrow dtype for each column.

Steps to reproduce are:

**on MySQL Create the following table:**

```
create database test;
CREATE TABLE test.user_role (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `user_id` int unsigned NOT NULL,
  `role_id` int unsigned NOT NULL,
  `organisation_id` int unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_role_index` (`user_id`,`role_id`),
  KEY `user_role_user_id_foreign` (`user_id`),
  KEY `user_role_role_id_foreign` (`role_id`)) ENGINE=InnoDB AUTO_INCREMENT=128 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Insert some sample data:**

  INSERT INTO `test`.`user_role`
(`id`,
`created_at`,
`updated_at`,
`user_id`,
`role_id`,
`organisation_id`)
VALUES
(1,
"2021-07-21 00:00:00",
"2021-07-21 00:00:00",
1,
1,
1);

  INSERT INTO `test`.`user_role`
(`id`,
`created_at`,
`updated_at`,
`user_id`,
`role_id`,
`organisation_id`)
VALUES
(2,
"2021-07-21 00:00:00",
"2021-07-21 00:00:00",
2,
2,
2);

**Python Script:**
import awswrangler as wr
import pandas as pd
import pymysql as pymysql
import traceback
import pyarrow as pa


con = pymysql.connect(host='<Host Name>',
                      user='<username>',
                      password='<password>',
                      database='<database>',
                      charset='utf8mb4')

dataset = pd.DataFrame()
try:

    dtype = {'id': pa.int32(),
            'created_at': pa.timestamp('us'),
            'updated_at': pa.timestamp('us'),
            'user_id': pa.int32(),
            'role_id': pa.int32(),
            'organisation_id': pa.int32()}

    dataset = wr.mysql.read_sql_query(
        sql=f"SELECT * FROM test.user_role",
        dtype=dtype,
        safe=True,
        con=con
    )
except Exception:
    print(traceback.format_exc())

**When running the script we can see the error:**

$python3 test_user_role.py 
Traceback (most recent call last):
  File "test_user_role.py", line 24, in <module>
    dataset = wr.mysql.read_sql_query(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awswrangler/mysql.py", line 202, in read_sql_query
    return _db_utils.read_sql_query(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awswrangler/_databases.py", line 218, in read_sql_query
    return _fetch_all_results(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awswrangler/_databases.py", line 196, in _fetch_all_results
    return _records2df(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awswrangler/_databases.py", line 141, in _records2df
    array = pa.array(obj=col_values, type=dtype[col_name], safe=safe)  # Creating Arrow array with dtype
  File "pyarrow/array.pxi", line 296, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
**TypeError: an integer is required (got type str)**

Python Version: Python 3.8.10
awswrangler            2.9.0               
pandas                 1.2.4               
pyarrow                2.0.0               

I'm facing the same issue when using aws data wrangler on MWAA
Please let me know if any additional information is required to reproduce the issue on your side.
Thanks in advance.

**Comment by maxispeicher** [comment]
I've just did a test with the most recent versions of `pyarrow` (4.0.1) and `pandas` (1.2.3) for `awswrangler==2.9.0` and there it works without any problems.
So it seems like there was a bug in one of these (most probable `pyarrow`) which was fixed in the meantime.

**Comment by maiconrocha** [comment]
Thanks a lot @maxispeicher. Unfortunately MWAA supports only up to pyarrow 2.0 so far: https://raw.githubusercontent.com/apache/airflow/constraints-2.0.2/constraints-3.7.txt
So it seems I'm stuck :(

**Comment by maiconrocha** [comment]
Actually, just tested with the recommended versions on my local machine and I'm still facing the issue:

pip3 list | grep pandas
pandas                 1.2.3               
pip3 list | grep pyarrow
pyarrow                4.0.1               
pip3 list | grep wrangler
awswrangler            2.9.0  

$ python3 test_user_role.py 
Traceback (most recent call last):
  File "test_user_role.py", line 24, in <module>
    dataset = wr.mysql.read_sql_query(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awswrangler/mysql.py", line 202, in read_sql_query
    return _db_utils.read_sql_query(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awswrangler/_databases.py", line 218, in read_sql_query
    return _fetch_all_results(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awswrangler/_databases.py", line 196, in _fetch_all_results
    return _records2df(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awswrangler/_databases.py", line 141, in _records2df
    array = pa.array(obj=col_values, type=dtype[col_name], safe=safe)  # Creating Arrow array with dtype
  File "pyarrow/array.pxi", line 306, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 141, in pyarrow.lib.pyarrow_internal_check_status
TypeError: an integer is required (got type str)

**Comment by maxispeicher** [comment]
Strange 🤔 
I've just created a fresh MySQL instance with engine version 8.0.23 and ran the script another time and it worked just fine. The print of the `dataset` variable looks like this:
```
   id created_at updated_at  user_id  role_id  organisation_id
0   1 2021-07-21 2021-07-21        1        1                1
1   2 2021-07-21 2021-07-21        2        2                2
```

**Comment by maiconrocha** [comment]
My RDS MySQL Version is also `8.0.23`.
What is your Python version?

**Comment by maxispeicher** [comment]
I did test it with `3.8.7` and `3.9.4`.

**Comment by maiconrocha** [comment]
```
try:
    dtype = {'id': pa.int32(),
     #       'created_at': pa.timestamp('us'),
     #       'updated_at': pa.timestamp('us'),
            'user_id': pa.int32(),
            'role_id': pa.int32(),
            'organisation_id': pa.int32()}
    dataset = wr.mysql.read_sql_query(
        sql=f"SELECT id,user_id,role_id,organisation_id FROM roster.user_role",
        dtype=dtype,
        safe=True,
        con=con
    )
    print (dataset)
except Exception:
    print(traceback.format_exc())
    
```
without timestamp columns it works

```
python3 test_user_role.py
   id  user_id  role_id  organisation_id
0   1        1        1                1
1   2        2        2                2
```

@maxispeicher  Can you confirm you create the table on mysql with `timestamp` data type?
Because from your result it seems you are using `date` and not `timestamp`

**Comment by maiconrocha** [comment]
@maxispeicher got the issue. When we have timestamp value as `"0000-00-00 00:00:00"` it generates the error.

if you insert one more row, 

```
  INSERT INTO `test`.`user_role`
(`id`,
`created_at`,
`updated_at`,
`user_id`,
`role_id`,
`organisation_id`)
VALUES
(3,
"0000-00-00 00:00:00",
"0000-00-00 00:00:00",
3,
3,
3);
```

You should face the issue.

**Comment by maxispeicher** [comment]
Yes you're right for the `"0000-00-00 00:00:00"` timestamp there is an error. However, this error is due to the fact that it is an invalid date and also is only insertable with `SQL_MODE='ALLOW_INVALID_DATES'`. `awswrangler` uses [pymysql](https://github.com/PyMySQL/PyMySQL) for interacting with MySQL databases and this package uses [convert_datetime](https://github.com/PyMySQL/PyMySQL/blob/6ccbecc1a0dfd04065b081950d2d35b1dac0aaa8/pymysql/converters.py#L189) for converting timestamps.
You can see the problem by executing 
```python
from pymysql.converters import convert_datetime
convert_datetime("2021-07-21 00:00:00")
# Out: datetime.datetime(2021, 7, 21, 0, 0)
convert_datetime("0000-00-00 00:00:00")
# Out: '0000-00-00 00:00:00'
```
Python can't create a datetime object for `"0000-00-00 00:00:00"` it is out of range for a valid date.

**Comment by maiconrocha** [comment]
Yes, I realised it @maxispeicher 
I will fix the data on the source to avoid this error on the framework.
Thanks a lot for your help and I hope the above discussion help others facing the same issue.
Cheers ✌️
