### ISSUE TITLE
redshift_connector.error.InterfaceError: {'S': 'FATAL', 'C': '28000', 'M': 'password authentication failed for user

### ISSUE THREAD

**Issue by nmduarteus** [awslabs/aws-data-wrangler#481]
Hi,

I have just upgraded awswrangler to 2.0.0 and moved from db.get_engine (which doesn't work anymore anyway) to redshift.connect and use glue connections.

While using the redshift.connect I am not able to connect using my glue connection - error is: redshift_connector.error.InterfaceError: {'S': 'FATAL', 'C': '28000', 'M': 'password authentication failed for user xxx

- When using the glue console to test the connection, it works fine.
- When using db client, works fine.
- When using awswrangler 1.x and db/catalog get_engine , it works fine.

Password has special characters.

UPDATE: after changing the password and removing special chars, the connection worked. Wondering if there is a way to include special chars and/or which ones can cause problems

thank you

**Comment by igorborgest** [comment]
Hi @nmduarteus , thanks for reporting it.

It already was fixed in our development branch (commit above). Could you give it a try?

```sh
pip install git+https://github.com/awslabs/aws-data-wrangler.git@feature/secrets-manager
```

**Comment by kvey** [comment]
@igorborgest This is currently still failing for me while using this branch, the change feels like it should've resolved the issue though.

> changing the password and removing special chars
still resolved the issue for me

**Comment by igorborgest** [comment]
Released on version [2.1.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.1.0)

**Comment by igorborgest** [comment]
Hi @kvey !

Please, notice that the Glue Catalog console does not require backslash escape unlike Python or SQL strings.

**Comment by nmduarteus** [comment]
Thanks for having a look and fixing it @igorborgest! Obrigado!
