### ISSUE TITLE
Unsupported Athena type: row

### ISSUE THREAD

**Issue by vfrank66** [awslabs/aws-data-wrangler#82]
I am getting this error when trying to run a simple query against AWS Athena

> Exception has occurred: UnsupportedType
> Unsupported Athena type: row

```python
import awswrangler 

database_name = "_results_database"
wrangler = awswrangler.Session(athena_ctas_approach=False)
dataframe = wrangler.pandas.read_sql_athena(
    sql='SELECT * FROM request_response',
    database=database_name
)
print('done')
```

If I try to limit the data to a single row in order to see if it has to do with a single partition by chance I get a different error, which may be related:

> Exception has occurred: ArrowNotImplementedError
> Reading lists of structs from Parquet files not yet supported: group: list<array_element: struct<header: struct<e_type: string, id2: string, p_id: string, r_id: string>, request: string, response: struct<appreturncode: int32, apperrors: string, resp_coll: string, rec_prpr: string>>>

```python
import awswrangler 

database_name = "{env}_facets_results_database".format(env="dev")
wrangler = awswrangler.Session(athena_ctas_approach=True)
dataframe = wrangler.pandas.read_sql_athena(
sql="SELECT * " +
" FROM _request_response AS fac " +
" WHERE \"fac\".\"id\" = '1000009'",
    database=database_name
)
print('done')
```

Maybe there isn't anything you can do though after reading this issue https://github.com/apache/arrow/issues/3371.

**Comment by igorborgest** [comment]
Let's address it in version 3.0.2!

**Comment by igorborgest** [comment]
Changing the plan a little bit. We will add support for nested types on version 1.0.0. Coming soon!

**Comment by igorborgest** [comment]
Hi! We will release AWS Data Wrangler 1.0.0 on `April 10` and we are collecting as much feedback as possible.

This issue should be resolved with this release. So, please test it if possible, and any feedback about the docs, the library or this specific functionality will be very welcome. 

- Install: `pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev-1.0.0`
- Docs: https://aws-data-wrangler.readthedocs.io/en/dev-1.0.0/
- Code: https://github.com/awslabs/aws-data-wrangler/tree/dev-1.0.0

**Comment by igorborgest** [comment]
Thank you for the contribution. Please, reopen the issue if it persists even after the version `1.0.0`.

**Comment by nivcoh** [comment]
version 2.8.0 still getting "`Exception: Unsupported Athena type: map"` while it running perfectly on AWS console or using dbeaver
